# This is a basic workflow to help you get started with Actions

name: Build Page

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    # Cypress Docker image with Chrome v80
    # and Firefox v73 pre-installed  cypress/browsers:node14.7.0-chrome84 cypress/browsers:node10.16.3-chrome80-ff73
    container: cypress/browsers:node14.7.0-chrome84

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment (v14)
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/fermium'

    - name: Install root dependencies
      uses: bahmutov/npm-install@v1

    - name: Check if the page builds
      run: npm run-script build
