# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**', '!master' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Cypress Docker image with Chrome v80
    # and Firefox v73 pre-installed
    container: cypress/browsers:node10.16.3-chrome80-ff73

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install root dependencies
      uses: bahmutov/npm-install@v1

    - name: Build
      run: npm run build

    - name: Prepare e2e tests
      run: npm run test:prepare

    # Cypress gh action includes npm install, caching, etc
    - name: Run e2e tests on Chrome
      uses: cypress-io/github-action@v2
      with:
        command: npm run test:chrome

    # Store failed test screenshots as artifact
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress
        path: |
          cypress/screenshots
          cypress/videos
        if-no-files-found: ignore